services:
    2pos:
        container_name: 2pos
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - ./:/app
        ports:
            - 9000:8080
        depends_on:
            - 2pos-database
    2pos-database:
        container_name: 2pos-database
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=default
            - MYSQL_USER=2pos
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data: ~
