services:
    2pos: # change this for every project
        container_name: 2pos # change this for every project
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - ./:/app
        ports:
            - 8080:8080
            - 8443:8443
